CREATE TABLE IF NOT EXISTS movies(

);
CREATE TABLE IF NOT EXISTS Theatres(
    id INT PRIMARY KEY AUTO_INCREMENT,
    name TEXT NOT NULL,
    location TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS Audis(
    id INT PRIMARY KEY AUTO_INCREMENT,
    name TEXT,
    theatre_id INTEGER NOT NULL,
    FOREIGN KEY(theatre_id) REFERENCES theatres(id)
);
CREATE TABLE IF NOT EXISTS seats(

);
CREATE TABLE IF NOT EXISTS shows(

);
CREATE TABLE IF NOT EXISTS tickets(

);
CREATE VIEW IF NOT EXISTS prices AS (

);
